# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='like_people',
            field=models.ManyToManyField(related_name='like_blogs', to='account.Profile'),
        ),
    ]
