# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 08:50
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to=account.models.Profile.get_user_avatar_folder),
        ),
    ]
