# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 09:31
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170203_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to=account.models.Profile.get_user_avatar_folder),
        ),
    ]
